export const yourSpec_0 = { "data": { "url": "http://localhost:3000/spreadsheet/insurance.csv", "schema": [{ "field": "age", "type": "numerical" }, { "field": "sex", "type": "categorical" }, { "field": "bmi", "type": "numerical" }, { "field": "children", "type": "numerical" }, { "field": "smoker", "type": "categorical" }, { "field": "region", "type": "categorical" }, { "field": "charges", "type": "numerical" }, { "field": "timestamp_charge", "type": "temporal" }] }, "actions": [{ "select": [{ "field": "charges", "aggregate": "count" }, { "field": "region" }], "groupby": [{ "field": "region" }], "filter": [] }, { "add": "config", "mode": "light", "width": 880, "height": 320 }, { "add": "chart", "mark": { "type": "bar" } }, { "add": "group", "actions": [{ "add": "encoding", "channel": "x", "field": "region" }, { "add": "encoding", "channel": "y", "field": "charges" }] }, { "add": "caption", "text": "the difference between southeast and northeast is 1020021.1799809998", "style": {} }, { "add": "annotation", "method": "fill", "target": [{ "field": "region", "value": "southeast" }] }, { "add": "annotation", "method": "fill", "target": [{ "field": "region", "value": "northeast" }] }] }

export const yourSpec_1 = { "data": { "url": "http://localhost:3000/spreadsheet/insurance.csv", "schema": [{ "field": "age", "type": "numerical" }, { "field": "sex", "type": "categorical" }, { "field": "bmi", "type": "numerical" }, { "field": "children", "type": "numerical" }, { "field": "smoker", "type": "categorical" }, { "field": "region", "type": "categorical" }, { "field": "charges", "type": "numerical" }, { "field": "timestamp_charge", "type": "temporal" }] }, "actions": [{ "select": [{ "field": "region" }], "groupby": [{ "field": "region" }], "filter": [] }, { "add": "config", "mode": "light", "width": 280, "height": 280 }, { "add": "chart", "mark": { "type": "unit" } }, { "add": "group", "actions": [{ "add": "encoding", "channel": "x", "field": "region" }] }] }

export const yourSpec_2 = { "data": { "url": "http://localhost:3000/spreadsheet/insurance.csv", "schema": [{ "field": "age", "type": "numerical" }, { "field": "sex", "type": "categorical" }, { "field": "bmi", "type": "numerical" }, { "field": "children", "type": "numerical" }, { "field": "smoker", "type": "categorical" }, { "field": "region", "type": "categorical" }, { "field": "charges", "type": "numerical" }, { "field": "timestamp_charge", "type": "temporal" }] }, "actions": [{ "select": [{ "field": "charges", "aggregate": "count" }, { "field": "region" }], "groupby": [{ "field": "region" }], "filter": [] }, { "add": "config", "mode": "light", "width": 280, "height": 280 }, { "add": "chart", "mark": { "type": "bar" } }, { "add": "group", "actions": [{ "add": "encoding", "channel": "x", "field": "region" }, { "add": "encoding", "channel": "y", "field": "charges" }] }] }

export const yourSpec_3 = { "data": { "url": "http://localhost:3000/spreadsheet/insurance.csv", "schema": [{ "field": "age", "type": "numerical" }, { "field": "sex", "type": "categorical" }, { "field": "bmi", "type": "numerical" }, { "field": "children", "type": "numerical" }, { "field": "smoker", "type": "categorical" }, { "field": "region", "type": "categorical" }, { "field": "charges", "type": "numerical" }, { "field": "timestamp_charge", "type": "temporal" }] }, "actions": [{ "select": [{ "field": "sex" }], "groupby": [{ "field": "sex" }], "filter": [] }, { "add": "config", "mode": "light", "width": 280, "height": 280 }, { "add": "chart", "mark": { "type": "unit" } }, { "add": "group", "actions": [{ "add": "encoding", "channel": "x", "field": "sex" }] }] }

export const yourSpec_4 = { "data": { "url": "http://localhost:3000/spreadsheet/insurance.csv", "schema": [{ "field": "age", "type": "numerical" }, { "field": "sex", "type": "categorical" }, { "field": "bmi", "type": "numerical" }, { "field": "children", "type": "numerical" }, { "field": "smoker", "type": "categorical" }, { "field": "region", "type": "categorical" }, { "field": "charges", "type": "numerical" }, { "field": "timestamp_charge", "type": "temporal" }] }, "actions": [{ "select": [{ "field": "charges", "aggregate": "avg" }], "groupby": [{ "field": "" }], "filter": [] }, { "add": "config", "mode": "light", "width": 300, "height": 300 }, { "add": "chart", "mark": { "type": "bar" } }, { "add": "caption", "text": "the avg of charges is", "style": { "font-color": "#FFCD00", "font-weight": "bold", "font-size": 20, "position": "top-left", "top-padding": 15 } }, { "add": "caption", "text": "1338", "style": { "font-color": "#AACDFF", "font-weight": "bold", "font-size": 24, "position": "top-center", "top-padding": 50 } }] }

export const yourSpec_5 = { "data": { "url": "http://localhost:3000/spreadsheet/insurance.csv", "schema": [{ "field": "age", "type": "numerical" }, { "field": "sex", "type": "categorical" }, { "field": "bmi", "type": "numerical" }, { "field": "children", "type": "numerical" }, { "field": "smoker", "type": "categorical" }, { "field": "region", "type": "categorical" }, { "field": "charges", "type": "numerical" }, { "field": "timestamp_charge", "type": "temporal" }] }, "actions": [{ "select": [{ "field": "charges", "aggregate": "sum" }], "groupby": [{ "field": "" }], "filter": [] }, { "add": "config", "mode": "light", "width": 400, "height": 400 }, { "add": "chart", "mark": { "type": "bar" } }, { "add": "caption", "text": "the sum of charges is", "style": { "font-color": "#FFCD00", "font-weight": "bold", "font-size": 20, "position": "top-left", "top-padding": 15 } }, { "add": "caption", "text": "17755824.990759", "style": { "font-color": "#AACDFF", "font-weight": "bold", "font-size": 24, "position": "top-center", "top-padding": 50 } }] }

export const yourSpec_6 = { "data": { "url": "http://localhost:3000/spreadsheet/insurance.csv", "schema": [{ "field": "age", "type": "numerical" }, { "field": "sex", "type": "categorical" }, { "field": "bmi", "type": "numerical" }, { "field": "children", "type": "numerical" }, { "field": "smoker", "type": "categorical" }, { "field": "region", "type": "categorical" }, { "field": "charges", "type": "numerical" }, { "field": "timestamp_charge", "type": "temporal" }] }, "actions": [{ "select": [{ "field": "charges", "aggregate": "count" }], "groupby": [{ "field": "" }], "filter": [] }, { "add": "config", "mode": "light", "width": 400, "height": 400 }, { "add": "chart", "mark": { "type": "bar" } }, { "add": "caption", "text": "the count of charges is", "style": { "font-color": "#FFCD00", "font-weight": "bold", "font-size": 20, "position": "top-left", "top-padding": 15 } }, { "add": "caption", "text": "1338", "style": { "font-color": "#AACDFF", "font-weight": "bold", "font-size": 24, "position": "top-center", "top-padding": 50 } }] }

