export const yourSpec_0 = {"data": {"url": "http://localhost:3000/spreadsheet/sales.csv", "schema": [{"field": "Brand", "type": "categorical"}, {"field": "Category", "type": "categorical"}, {"field": "Sales", "type": "numerical"}, {"field": "timestamp_category", "type": "temporal"}, {"field": "timestamp_sale", "type": "temporal"}]}, "actions": [{"select": [{"field": "Sales", "aggregate": "count"}], "groupby": [{"field": ""}], "filter": []}, {"add": "config", "mode": "light", "width": 176, "height": 111}, {"add": "chart", "mark": {"type": "bar"}}, {"add": "caption", "text": "the count of Sales is", "style": {"font-color": "#FFCD00", "font-weight": "bold", "font-size": 20, "position": "top-left", "top-padding": 15}}, {"add": "caption", "text": "275", "style": {"font-color": "#AACDFF", "font-weight": "bold", "font-size": 24, "position": "top-center", "top-padding": 50}}]}

export const yourSpec_1 = {"data": {"url": "http://localhost:3000/spreadsheet/sales.csv", "schema": [{"field": "Brand", "type": "categorical"}, {"field": "Category", "type": "categorical"}, {"field": "Sales", "type": "numerical"}, {"field": "timestamp_category", "type": "temporal"}, {"field": "timestamp_sale", "type": "temporal"}]}, "actions": [{"select": [{"field": "Sales", "aggregate": "sum"}], "groupby": [{"field": ""}], "filter": []}, {"add": "config", "mode": "light", "width": 176, "height": 111}, {"add": "chart", "mark": {"type": "bar"}}, {"add": "caption", "text": "the sum of Sales is", "style": {"font-color": "#FFCD00", "font-weight": "bold", "font-size": 20, "position": "top-left", "top-padding": 15}}, {"add": "caption", "text": "21921768", "style": {"font-color": "#AACDFF", "font-weight": "bold", "font-size": 24, "position": "top-center", "top-padding": 50}}]}

export const yourSpec_2 = {"data": {"url": "http://localhost:3000/spreadsheet/sales.csv", "schema": [{"field": "Brand", "type": "categorical"}, {"field": "Category", "type": "categorical"}, {"field": "Sales", "type": "numerical"}, {"field": "timestamp_category", "type": "temporal"}, {"field": "timestamp_sale", "type": "temporal"}]}, "actions": [{"select": [{"field": "Sales", "aggregate": "count"}, {"field": "Category"}], "groupby": [{"field": "Category"}], "filter": []}, {"add": "config", "mode": "light", "width": 176, "height": 111}, {"add": "chart", "mark": {"type": "bar"}}, {"add": "group", "actions": [{"add": "encoding", "channel": "x", "field": "Category"}, {"add": "encoding", "channel": "y", "field": "Sales"}]}, {"add": "caption", "text": "", "style": {}}, {"add": "annotation", "method": "fill", "target": [{"field": "Category", "value": "Fullsize"}]}, {"add": "annotation", "method": "fill", "target": [{"field": "Category", "value": "SUV"}]}]}

export const yourSpec_3 = {"data": {"url": "http://localhost:3000/spreadsheet/sales.csv", "schema": [{"field": "Brand", "type": "categorical"}, {"field": "Category", "type": "categorical"}, {"field": "Sales", "type": "numerical"}, {"field": "timestamp_category", "type": "temporal"}, {"field": "timestamp_sale", "type": "temporal"}]}, "actions": [{"select": [{"field": "Sales", "aggregate": "sum"}, {"field": "timestamp_category"}], "groupby": [{"field": "timestamp_category"}], "filter": []}, {"add": "config", "mode": "light", "width": 640, "height": 640}, {"add": "chart", "mark": {"type": "bar"}}, {"add": "group", "actions": [{"add": "encoding", "channel": "x", "field": "timestamp_category"}, {"add": "encoding", "channel": "y", "field": "Sales"}]}, {"add": "caption", "text": "", "style": {}}, {"add": "annotation", "method": "fill", "target": [{"field": "timestamp_category", "value": "2001/9/5"}]}, {"add": "annotation", "method": "fill", "target": [{"field": "timestamp_category", "value": "2031/8/1"}]}]}

export const yourSpec_4 = {"data": {"url": "http://localhost:3000/spreadsheet/sales.csv", "schema": [{"field": "Brand", "type": "categorical"}, {"field": "Category", "type": "categorical"}, {"field": "Sales", "type": "numerical"}, {"field": "timestamp_category", "type": "temporal"}, {"field": "timestamp_sale", "type": "temporal"}]}, "actions": [{"select": [{"field": "Sales", "aggregate": "sum"}, {"field": "Category"}], "groupby": [{"field": "Category"}], "filter": []}, {"add": "config", "mode": "light", "width": 280, "height": 280}, {"add": "chart", "mark": {"type": "bar"}}, {"add": "group", "actions": [{"add": "encoding", "channel": "x", "field": "Category"}, {"add": "encoding", "channel": "y", "field": "Sales"}]}, {"add": "caption", "text": "", "style": {}}, {"add": "annotation", "method": "fill", "target": [{"field": "Category", "value": "SUV"}]}, {"add": "annotation", "method": "fill", "target": [{"field": "Category", "value": "Pickup"}]}]}

export const yourSpec_5 = {"data": {"url": "http://localhost:3000/spreadsheet/sales.csv", "schema": [{"field": "Brand", "type": "categorical"}, {"field": "Category", "type": "categorical"}, {"field": "Sales", "type": "numerical"}, {"field": "timestamp_category", "type": "temporal"}, {"field": "timestamp_sale", "type": "temporal"}]}, "actions": [{"select": [{"field": "Brand"}], "groupby": [{"field": "Brand"}], "filter": []}, {"add": "config", "mode": "light", "width": 280, "height": 280}, {"add": "chart", "mark": {"type": "unit"}}, {"add": "group", "actions": [{"add": "encoding", "channel": "x", "field": "Brand"}]}]}

export const yourSpec_6 = {"data": {"url": "http://localhost:3000/spreadsheet/sales.csv", "schema": [{"field": "Brand", "type": "categorical"}, {"field": "Category", "type": "categorical"}, {"field": "Sales", "type": "numerical"}, {"field": "timestamp_category", "type": "temporal"}, {"field": "timestamp_sale", "type": "temporal"}]}, "actions": [{"select": [{"field": "Sales", "aggregate": "count"}, {"field": "Brand"}], "groupby": [{"field": "Brand"}], "filter": []}, {"add": "config", "mode": "light", "width": 280, "height": 280}, {"add": "chart", "mark": {"type": "arc"}}, {"add": "group", "actions": [{"add": "encoding", "channel": "theta", "field": "Sales"}, {"add": "annotation", "method": "label", "target": []}]}, {"add": "annotation", "method": "fill", "target": [{"field": "Brand", "value": "Ford"}]}, {"add": "caption", "text": "", "style": {}}, {"add": "annotation", "method": "fill", "target": [{"field": "Brand", "value": "Ford"}]}]}

