export const yourSpec_0 = {"data": {"url": "http://localhost:3000/spreadsheet/USElection.csv", "schema": [{"field": "state", "type": "categorical"}, {"field": "candidate", "type": "categorical"}, {"field": "party", "type": "categorical"}, {"field": "votes", "type": "numerical"}, {"field": "timestamp_state", "type": "temporal"}, {"field": "timestamp_votes", "type": "temporal"}]}, "actions": [{"select": [{"field": "votes", "aggregate": "sum"}], "groupby": [{"field": ""}], "filter": []}, {"add": "config", "mode": "light", "width": 176, "height": 111}, {"add": "chart", "mark": {"type": "bar"}}, {"add": "caption", "text": "the sum of votes is", "style": {"font-color": "#FFCD00", "font-weight": "bold", "font-size": 20, "position": "top-left", "top-padding": 15}}, {"add": "caption", "text": "150219171", "style": {"font-color": "#AACDFF", "font-weight": "bold", "font-size": 24, "position": "top-center", "top-padding": 80}}]}

export const yourSpec_1 = {"data": {"url": "http://localhost:3000/spreadsheet/USElection.csv", "schema": [{"field": "state", "type": "categorical"}, {"field": "candidate", "type": "categorical"}, {"field": "party", "type": "categorical"}, {"field": "votes", "type": "numerical"}, {"field": "timestamp_state", "type": "temporal"}, {"field": "timestamp_votes", "type": "temporal"}]}, "actions": [{"select": [{"field": "party"}], "groupby": [{"field": "party"}], "filter": []}, {"add": "config", "mode": "light", "width": 176, "height": 111}, {"add": "chart", "mark": {"type": "unit"}}, {"add": "group", "actions": [{"add": "encoding", "channel": "x", "field": "party"}]}]}

export const yourSpec_2 = {"data": {"url": "http://localhost:3000/spreadsheet/USElection.csv", "schema": [{"field": "state", "type": "categorical"}, {"field": "candidate", "type": "categorical"}, {"field": "party", "type": "categorical"}, {"field": "votes", "type": "numerical"}, {"field": "timestamp_state", "type": "temporal"}, {"field": "timestamp_votes", "type": "temporal"}]}, "actions": [{"select": [{"field": "candidate"}], "groupby": [{"field": "candidate"}], "filter": []}, {"add": "config", "mode": "light", "width": 176, "height": 111}, {"add": "chart", "mark": {"type": "unit"}}, {"add": "group", "actions": [{"add": "encoding", "channel": "x", "field": "candidate"}]}]}

export const yourSpec_3 = {"data": {"url": "http://localhost:3000/spreadsheet/USElection.csv", "schema": [{"field": "state", "type": "categorical"}, {"field": "candidate", "type": "categorical"}, {"field": "party", "type": "categorical"}, {"field": "votes", "type": "numerical"}, {"field": "timestamp_state", "type": "temporal"}, {"field": "timestamp_votes", "type": "temporal"}]}, "actions": [{"select": [{"field": "votes", "aggregate": "count"}, {"field": "candidate"}], "groupby": [{"field": "candidate"}], "filter": []}, {"add": "config", "mode": "light", "width": 176, "height": 111}, {"add": "chart", "mark": {"type": "arc"}}, {"add": "group", "actions": [{"add": "encoding", "channel": "theta", "field": "votes"}, {"add": "annotation", "method": "label", "target": []}]}, {"add": "annotation", "method": "fill", "target": [{"field": "candidate", "value": "Biden"}]}, {"add": "caption", "text": "", "style": {}}, {"add": "annotation", "method": "fill", "target": [{"field": "candidate", "value": "Biden"}]}]}

export const yourSpec_4 = {"data": {"url": "http://localhost:3000/spreadsheet/USElection.csv", "schema": [{"field": "state", "type": "categorical"}, {"field": "candidate", "type": "categorical"}, {"field": "party", "type": "categorical"}, {"field": "votes", "type": "numerical"}, {"field": "timestamp_state", "type": "temporal"}, {"field": "timestamp_votes", "type": "temporal"}]}, "actions": [{"select": [{"field": "votes", "aggregate": "sum"}, {"field": "candidate"}], "groupby": [{"field": "candidate"}], "filter": []}, {"add": "config", "mode": "light", "width": 445, "height": 380}, {"add": "chart", "mark": {"type": "arc"}}, {"add": "group", "actions": [{"add": "encoding", "channel": "theta", "field": "votes"}, {"add": "annotation", "method": "label", "target": []}]}, {"add": "annotation", "method": "fill", "target": [{"field": "candidate", "value": "Trump"}]}, {"add": "caption", "text": "", "style": {}}, {"add": "annotation", "method": "fill", "target": [{"field": "candidate", "value": "Trump"}]}]}

export const yourSpec_5 = {"data": {"url": "http://localhost:3000/spreadsheet/USElection.csv", "schema": [{"field": "state", "type": "categorical"}, {"field": "candidate", "type": "categorical"}, {"field": "party", "type": "categorical"}, {"field": "votes", "type": "numerical"}, {"field": "timestamp_state", "type": "temporal"}, {"field": "timestamp_votes", "type": "temporal"}]}, "actions": [{"select": [{"field": "votes", "aggregate": "sum"}, {"field": "candidate"}], "groupby": [{"field": "candidate"}], "filter": []}, {"add": "config", "mode": "light", "width": 445, "height": 380}, {"add": "chart", "mark": {"type": "bar"}}, {"add": "group", "actions": [{"add": "encoding", "channel": "x", "field": "candidate"}, {"add": "encoding", "channel": "y", "field": "votes"}]}, {"add": "caption", "text": "", "style": {}}, {"add": "annotation", "method": "fill", "target": [{"field": "candidate", "value": "Biden"}]}, {"add": "annotation", "method": "fill", "target": [{"field": "candidate", "value": "Trump"}]}]}

