export default {
    // Story
    UPLOAD_DATA: 'UPLOAD_DATA',
    GENERATE_STORY: 'GENERATE_STORY',
    CHANGE_STORY_TITLE: 'CHANGE_STORY_TITLE',
    CHANGE_STORY_KEYPOINT: 'CHANGE_STORY_KEYPOINT',
    CHANGE_FACT_TITLE: 'CHANGE_FACT_TITLE',
    CHANGE_FACT_CAPTION: 'CHANGE_FACT_CAPTION',
    CHANGE_FACT_LIST:'CHANGE_FACT_LIST',
    CHANGE_ORIGIN_FACT_LIST:'CHANGE_ORIGIN_FACT_LIST',
    CHANGE_ANI_FACT_LIST:'CHANGE_ANI_FACT_LIST',

    ADD_DATAFACT: 'ADD_DATAFACT',
    CHANGE_DATAFACT: 'CHANGE_DATAFACT',
    REORDER_DATASTORY: 'REORDER_DATASTORY',
    SET_FILEPATH:'SET_FILEPATH',
    SET_CIRCLE_INDEX:'SET_CIRCLE_INDEX',
    // UPDATE_PROGRESS: 'UPDATE_PROGRESS',//生成进度
    
    //user
    // UPDATE_USER_INFO: 'UPDATE_USER_INFO',
    UPDATE_USER_OPERATION: 'UPDATE_USER_OPERATION',
    // UPDATE_CONVERT_TYPE: 'UPDATE_CONVERT_TYPE',
    UPDATE_LOCALE: 'UPDATE_LOCALE',


    //edit panel
    SET_FACT_INDEX: 'SET_FACT_INDEX',
    SET_EDITING_CHARTMODE:'SET_EDITING_CHARTMODE',
    SET_EDITING_BREAKDOWN:'SET_EDITING_BREAKDOWN',
    SET_EDITING_MEASURE:'SET_EDITING_MEASURE',
    SET_EDITING_SUBSPACE:'SET_EDITING_SUBSPACE',
    DELETE_DATAFACT:'DELETE_DATAFACT',
    SET_VISUALIZE_GENRE:'SET_VISUALIZE_GENRE',
    SET_VISUALIZE_TEMPLATE:'SET_VISULIZE_TEMPLATE',
    CHANGEDFILE_LIST:'CHANGEDFILE_LIST',
    IMAGE_LIST1:'IMAGE_LIST1',
    IMAGE_LIST2:'IMAGE_LIST2',
    IMAGE_LIST3:'IMAGE_LIST3',
    G1_MAIN_CHART:"G1_MAIN_CHART",
    G2_MAIN_CHART:"G2_MAIN_CHART",
    G3_MAIN_CHART:"G3_MAIN_CHART",
    DRAGED_POINT:"DRAGED_POINT",



    //init edit
    // SET_PARSED_FILE_DATA: 'SET_PARSED_FILE_DATA',
    // SET_SCALE: 'SET_SCALE',

    // //before generate
    // SET_TASK: 'SET_TASK',


    // //time seires
    // SET_SEQUENCE: "SET_SEQUENCE",
    // SET_REDUNDANT: "SET_REDUNDANT",
    // ADD_SEGMENTS_INSIGHTS: "ADD_SEGMENTS_INSIGHTS",

    // CHANGE_BTN_STATE: "CHANGE_BTN_STATE",
    // ADD_EMPTY_CARD: "ADD_EMPTY_CARD",
    // CHANGE_CRAD_LOCATION: "CHANGE_CRAD_LOCATION",
    // REMOVE_CARD: "REMOVE_CARD",
    // FIX_CARD: "FIX_CARD",
    // SET_SELECTED_CARD_INDEX: "SET_SELECTED_CARD_INDEX",


    // //recommend list
    // SET_SELECTED_RECOMMEND_CARD: "SET_SELECTED_RECOMMEND_CARD",
    // REMOVE_RECOMMEND_CARD: "REMOVE_RECOMMEND_CARD",
    // ADD_RECOMMEND_LIST: 'ADD_RECOMMEND_LIST',

    // //pop insight card
    // SET_POP_CARD_START: "SET_POP_CARD_START",
    // SET_POP_INSIGHTS: "SET_POP_INSIGHTS",

    // SET_TOOLTIP_CONTAINER: 'SET_TOOLTIP_CONTAINER',

    // //configure columsn
    // SET_CONFIGURE_COLUMNS: 'SET_CONFIGURE_COLUMNS',
    // SET_CONFIGURE_TYPE: 'SET_CONFIGURE_TYPE',
    // SET_CONFIGURE_TIME: 'SET_CONFIGURE_TIME',
    // SET_CONFIGURE_BREAKDOWN: 'SET_CONFIGURE_BREAKDOWN',

    // UPDATE_FILEURL_AND_DATA: 'UPDATE_FILEURL_AND_DATA',
    // UPDATE_COLUMNS_AND_RANGE: 'UPDATE_COLUMNS_AND_RANGE',

    // SET_PROCESS_TIME: 'SET_PROCESS_TIME',
    // SET_PROCESS_GRANULARITY: 'SET_PROCESS_GRANULARITY',
    // SET_PROCESS_COLUMNS: 'SET_PROCESS_COLUMNS'

}